// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7d966c41-af06-4da9-ac86-7a1ca559d2aa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IOmU4Emox",
    "aws_user_pools_web_client_id": "2sku73185cbgss48a3g67sdp8d"
};


export default awsmobile;
